name: Android CI

on:
  push:
    branches: [ "main" ] # Поменяй на "master", если главная ветка называется так

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Если все файлы сборки (gradlew, build.gradle.kts) лежат в подпапке app, 
    # эта строчка заставит GitHub Actions работать прямо внутри неё:
    defaults:
      run:
        working-directory: ./app

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlehw
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
